### ISSUE TITLE
Publish prebaked oci image in github packages

### ISSUE THREAD

**Issue by JeroenKnoops** [edumserrano/github-issue-forms-parser#6]
# Problem

Currently everytime we run this action, the entire project is being build and the entire dotnet build environment is being downloaded. This takes some time.

## Proposed solution
On changes in this repository publish the build artifact in this repository. Refer to that build artifact in the `action.yml`.

**Comment by JeroenKnoops** [comment]
If you want I can create a PR for this.

**Comment by edumserrano** [comment]
Sounds like a good idea. Haven't tried to publish an image to github packages yet. What you suggesting is just a github workflow to do that or is there more to it?

I'd appreciate the PR yes.

**Comment by JeroenKnoops** [comment]
I've created an example in a fork: https://github.com/JeroenKnoops/github-issue-forms-parser/pull/1/files

On changes pushed to `main` it will build the project and pushes the OCI container to github packages. In the example above, you need to replace to REGISTRY_URL and GITHUB_ORGANIZATION from `jeroenknoops` to `edumserrano`.

In the `action.yml` it will use that container instead of recreating it all the time.

When debugging a feature in a branch, you can switch back to `Dockerfile` in `action.yml` in a branch and use that in debugging. Then you will get the current workflow again with a fresh clean build everytime you run it.

Please let me know if this was of any help.

**Comment by edumserrano** [comment]
I merged your PR on this but when I tried to run the workflow I was getting this error:

![image](https://user-images.githubusercontent.com/15857357/209394671-dc2c835e-48ed-4718-bb0a-c50ed19256c0.png)

You can see it [here](https://github.com/edumserrano/github-issue-forms-parser/actions/runs/3767674749/jobs/6405438035).

Anyway, I've checked the docs on how to publish a Docker Image to Github Packages and [followed the docs](https://docs.github.com/en/actions/publishing-packages/publishing-docker-images#publishing-images-to-github-packages).

**Comment by edumserrano** [comment]
I've also updated the docs regarding the workflow changes:
- [Documentation for new publish-docker-image workflow](https://github.com/edumserrano/github-issue-forms-parser/blob/main/docs/dev-notes/workflows/publish-docker-image.md)
- [Added note to the documentation about the test action workflow](https://github.com/edumserrano/github-issue-forms-parser/blob/main/docs/dev-notes/workflows/test-action-workflow.md)

**Comment by edumserrano** [comment]
Did a test PR to make sure the checks are all working as expected with this change. See #8

**Comment by edumserrano** [comment]
Published [version 1.3.0](https://github.com/edumserrano/github-issue-forms-parser/releases/tag/v1.3.0) of this action that  uses the Docker image published to GitHub packages.

**Comment by edumserrano** [comment]
I've also added a workflow to clean up old Docker images from the GitHub registry. See:
- [Documentation](https://github.com/edumserrano/github-issue-forms-parser/blob/main/docs/dev-notes/workflows/package-retention-policy.md)
- [Workflow](https://github.com/edumserrano/github-issue-forms-parser/actions/workflows/package-retention-policy.yml)

**Comment by edumserrano** [comment]
I believe everything required by this issue has been done. Let me know if there's something missing.

**Comment by JeroenKnoops** [comment]
The docker-ci-scripts@v5.0.0 had an error. Version 5.1.0 has a fix for that: https://github.com/philips-software/docker-ci-scripts/releases/tag/v5.1.0

But the current workflow is also working. Thanks for accepting this change, this makes the action way faster! :)
